use_frameworks!

platform :ios, '12.0'

target 'EVOLibrary_Example' do
#  pod 'EVOLibrary', :git => 'https://github.com/EvenZhu/EVOLibrary.git'
  pod 'EVOLibrary', :path => '../'

  target 'EVOLibrary_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
